use std::env;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = PathBuf::from(&out_dir);

    // Check if glslangValidator is available (from glslang-tools package)
    let compiler_available = Command::new("glslangValidator")
        .arg("--version")
        .output()
        .is_ok();

    if compiler_available {
        println!("cargo:warning=Compiling matrix_multiply.glsl with glslangValidator...");
        
        let shader_src = "src/matrix_multiply.glsl";
        let spirv_out = out_path.join("matrix_multiply.spv");
        
        let output = Command::new("glslangValidator")
            .arg("-V")
            .arg("-S")
            .arg("comp")  // Specify compute shader stage
            .arg(shader_src)
            .arg("-o")
            .arg(&spirv_out)
            .output();
        
        match output {
            Ok(status) if status.status.success() => {
                println!("cargo:warning=✓ Shader compiled successfully!");
                // Read compiled SPIR-V
                let spirv_bytes = std::fs::read(&spirv_out)
                    .expect("Failed to read compiled SPIR-V");
                
                // Generate Rust code from SPIR-V - just the vec content, not the function
                let mut rust_code = String::from("// Auto-generated SPIR-V bytecode from matrix_multiply.glsl\n");
                rust_code.push_str("// Generated by build.rs using glslangValidator\n");
                rust_code.push_str("vec![\n");
                
                for (i, chunk) in spirv_bytes.chunks(4).enumerate() {
                    if i % 8 == 0 && i > 0 {
                        rust_code.push_str("\n");
                    }
                    if chunk.len() == 4 {
                        let word = u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
                        rust_code.push_str(&format!("        0x{:08x},", word));
                    }
                }
                
                rust_code.push_str("\n]\n");
                
                // Write to src/shader_compiled.rs
                let shader_codegen = PathBuf::from("src/shader_compiled.rs");
                std::fs::write(&shader_codegen, rust_code)
                    .expect("Failed to write generated SPIR-V code");
                    
                println!("cargo:warning=✓ Generated SPIR-V bytecode ({} bytes)", spirv_bytes.len());
            }
            _ => {
                println!("cargo:warning=⚠ Shader compilation failed. Using embedded SPIR-V fallback.");
                // Create fallback file with empty vec
                std::fs::write("src/shader_compiled.rs", 
                    "// Shader compilation failed, using fallback\nvec![]\n")
                    .ok();
            }
        }
    } else {
        println!("cargo:warning=⚠ glslangValidator not found in PATH. Using embedded SPIR-V fallback.");
        println!("cargo:warning=To enable shader compilation, install glslang-tools:");
        println!("cargo:warning=  - Linux: apt-get install glslang-tools");
        println!("cargo:warning=  - Or: https://www.lunarg.com/vulkan-sdk/");
        
        // Create fallback file with empty vec
        std::fs::write("src/shader_compiled.rs", 
            "// glslangValidator not found, using fallback\nvec![]\n")
            .ok();
    }

    // Rerun if shader changes
    println!("cargo:rerun-if-changed=src/matrix_multiply.glsl");
}
